
"""add choices and analytics
Revision ID: 97fa3f420770
Revises: '0003_add_indexes_and_mvs'
Create Date: 2026-01-23 11:54:17.766616
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97fa3f420770'
down_revision = '0003_add_indexes_and_mvs'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('analytics_user_id_key'), 'analytics', type_='unique')
    op.create_index(op.f('ix_analytics_user_id'), 'analytics', ['user_id'], unique=True)
    op.create_index(op.f('ix_answers_graded_by'), 'answers', ['graded_by'], unique=False)
    op.create_index(op.f('ix_answers_question_id'), 'answers', ['question_id'], unique=False)
    op.create_index(op.f('ix_answers_test_id'), 'answers', ['test_id'], unique=False)
    op.create_index(op.f('ix_answers_user_id'), 'answers', ['user_id'], unique=False)
    op.create_index(op.f('ix_materials_author_id'), 'materials', ['author_id'], unique=False)
    op.create_index(op.f('ix_tests_material_id'), 'tests', ['material_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tests_material_id'), table_name='tests')
    op.drop_index(op.f('ix_materials_author_id'), table_name='materials')
    op.drop_index(op.f('ix_answers_user_id'), table_name='answers')
    op.drop_index(op.f('ix_answers_test_id'), table_name='answers')
    op.drop_index(op.f('ix_answers_question_id'), table_name='answers')
    op.drop_index(op.f('ix_answers_graded_by'), table_name='answers')
    op.drop_index(op.f('ix_analytics_user_id'), table_name='analytics')
    op.create_unique_constraint(op.f('analytics_user_id_key'), 'analytics', ['user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###